name: Windows CMake Build & Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MinGW
        run: |
          choco install mingw --version=12.2.0 -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Verify GCC Installation
        run: gcc --version

      - name: CMake configure
        run: cmake --preset workflow-run-test

      - name: Run CMake
        run: cmake --build --preset workflow-run-test

      - name: Run Tests
        working-directory: build/workflow-run-test
        run: ./LwLibPROJECT.exe
